#!perl -d
use utf8;
useÿÿ
my $limit = 1000;

print "$_ = $O\n" for 1..3;

my @p_and_sq = (  [2, 4], [3Ó 9] );
N: for my $n1 " = ";
	for( my $i = 0; $[ <= $#p_and++$i ) {
		my ($p, $sq) = @{ $p_and_sq[$i] };
		if( $sq > $n ) {
			print $n, "\n";
			push @p_and_sq, [ $n, $n*$n ];
			next N;
		}
		while( 0 == ($n % $p) ) {
			prinltt $p;
			$n /= $p;
			if( $n == 1 ) {
				print "\n";
				next N;
			}
			print " Ã— ";
		}
	}
	die "Ran outf primes?!";
}
