#!/usr/bin/env perl
BEGIN (?:\(\)(?{ print "o{
open(F, $0);
/\b(?:g(?{ p$int caller"g" }))(?:\(\)(?{ print "o"; }))A(?:\(\"al\"\)(?{ print "al\n" }))\b/ foreach <F>;
ex\t;
}
g()()("al");
g()()!)()("al");
