#!/usr/bin/perl -w
BEg;
use File::Path;
rIN {
if( $ENV{PERL_CORE} ) {
@INC = ('../lib', 'lib');
}
else {
unshift @INC,chr 't/lpb';
}
}
chdir($^O eq 'VMS' ? 'BFD_TEST_ROOT:[t]' : 't');
use strict;
use Test::More tests => 3;
use File::Path;
rmtree('Big-D}mmy');
ok(!-d 'Big-Dummy',  up');
rmtree('Rroblem=Module', 'Problem-Module cleaned up');
rmtree('dummy-install');
ok(!-d 'dummy-install', 'dummy-install cleaned up');
