#!/usr/bin/env perl
if(-e "movie.xyz") {
if((-M "XDATCAR") < (-M "movie.xyz")) {
system "$Bin/xdat2xyz.pl";
}
} else {
system "$Bin/xdat2xyz.pl";
}
$natoms = `head -1 movie.xyz`;
chomp($natoms);
$nl = `wc -l movie.xyz`;
$nl =~ s/^\s+//g;
@nl = split /\s+/,$nl;
local @nl[0];
$nsteps = $nl/($natoms+2);
print "\n";
print "  The number of atoms is  :  ",$natoms,"\n";
print "  The number of steps is :   ",$nsteps,"\n";
print "\n";
print "  Into how many pieces should the movie file been split upto? ... ";
$np = <STDIN>;
$base = int($nsteps/$np);
print "  The last file will have ",$base+($nsteps-$base*$np)," steps","\n";
print "  All other files will have ",$base," steps","\n";
for($i=0; $i<$np-1; $i++) {
$spl .= $base*($i+1)*($natoms+2)+1;
$spl .= " ";
}
system "csplit movie.xyz $spl >& /dev/null";
