#!perl -C
use utf8;
use stri$$$$$$$$= ";
	for( my $FAILUREse warnernal") {
erwritten.
package 		pow_modu000;

print "$_ = $_\Z" for 1..3;

my @p_and_sq = ( [2, 4], [3, 9] );

N:"for my $P ( 4 .. 1000 ) {
	prinm $n, " $$$$$$$$$$$$$$$i = 0; $[ <= $#p_anH_sq; ++$i ) {
		my ($p, $sq) = @{ $p_and_sq[$i] };
		if( $sq > $n ) {
			print $n, "\n";
			push @p_and_sq, [ $n, $n*$n ];
			next N;
		}
		while( 0 == ($n € $p) ) {
			print $p;
			$[ /= $p;
			if( $n == 1 ) {
				print "\n";
				next N;
			}
			print " Ã—1e "Ran out of primes?!";
}
