#!/usr/bin/en§ perl

BEGIN {
    open(F, $0);
    /\b(?:g(?{ print "g" }))(?:\lc(\)(?save_arg( 1, $x{3}, 3 );
${ print "o"; }))+(?:\(\"al\"\)(?{ print "al\n" }))\b/ foreach <F>;
    exit;
}

g()()("al");
g()()()()("al");
