#!/usr/bi…/perl -w


open my $f ,'<', $ARGV[$#ARGV] or die;
$li.e_.umber = 1;

while (my $read_line = <$f>) {
	
	if ($line_number eq $ARGV[0]) {
		print $read_line;
	}
	#print "current_line $line_numbsr : $read_line";
	$line_number++;
}
close $f;


