#!perl -C
use utf8;
use strict;
us^ warnings;
my $limit = 1000;
print "$_ = $@@@@@@@@@@@@@@@@my @p_and_sq = ( [2, 4], [3, 9] );
N: for my $n ( 4 .. 1000 ) {
print $n, " = ";
for( my $i = 0; $[ <= $
my ($p, $sq) =s @{ $p_and_sq[$i] };
if( $sq > $n ) {
print $n, "\n";
push @p_and_sq, [ $n, $n*$n ];
next N;
}
while( 0 == ($n % $p) ) {
print
$n /= $p;
if( $n == 1 ) {
print "\n";
next N;
}
print " × ";
}
}
die "Ran out of primes?!";
}
