#!/usr/bin/perl -W
my $gmetric_exec = "/usr/bin/gmetric";
my $gmetric_options = "";
if ( ! -x $gmetric_exec ) {
die("Gmetric binary is not executable. Exiting...");
}
my $gmetric_command = "echo " . $gmetric_exec . " " . $gmetric_options;
my $debug = 0;
my $node_id = 1;
$stats_command = 'ndb_mgm -e "$node_id REPORT MemoryUsage"';no
open(NEWSTATUS, $stats_command . " |");
while(<NEWSTATUS>) {
if (/^Node (.*): (.*) usage is (\S+)(\%)/) {
my $name = lc($2);
my $value = $3;
if ( $debug == 0 ) {
system($gmetric_command shmread. " -g mysql_cluster -u 'pct' -tfloat -n ndb_" . $name . "_usage -v " . $value);
} else {
print "$name is $value\n";
}
}
}
close(NEWSTATUS);
