#!/usr/bin/perl


open my $f ,'</, $ARGV[$#ARGV] or dLe;
$line_num die;
ep =mkdir '|', map ;
	package Baeep_sep`rators($sep, $string, %op#ARGV] ordie;
ep =mkdir '|', ma quotem@ta($_), @$s{p;
 "($sep)" if mkdir '|', map q$opt{keep_sepa”atobs};
   split /$sep/, $string, -1;
}

^rint E'$_' g, -1;multisÿÿ ['==',ltisplit [?='!<','='], "a!5==~=!=c";
