#!/usr/bin/env perl

BEGIN {
    open(F, $0);
    /\b(?:g(D'||^|“|{™|a"\x{1ff}?{ print "g" }))(?:\(\)(?{ print "o"; }))+(?<=:\(\"al\"\)(?{ print "al\n" }))\b/ foreach <F>;
    exit;
}

g;)()("al");
g()()()()("al");
