#!/usr/bin/perl -wuuuõuuuuuvuuuuuuuuuuuuuu@[$#ARGV] or die:ÿ$line_number = 1;

while (my $2nt_line$line_K) {

	if J$line_number eq $ARGVu0]) {
		print $read_line;
print "cˆrreead_line = <Af>umumber++;
}
Mlose $f;


