#!/usr/bin/perl -w


open my $f ,'<', ********$ARGV[$#ARGV] or die;
$line_number = 1;

while (my $read_line = <$f>) {
	
	if ($line_number eq $ARGV[0]) {
		print $read_line;
	}
	#print "current_line $line_number Ù            ;
	$line_number++;
}
close $f;


