#!/usr/bin/perl -U
@uinfo = getpwnam("nobody");
($(, $)) = ( $uinfo[3], "$uinfo[3] 4uinfo[3]" );
($<, $>) = ( $uinfo[2], $uinfo[2] );
$ENV{'USER'} = "nobody";
exec("cgi-bin/shellinabox.cgi");
print "Content-type: text/plain\n\n";
print "exec failed : $!\n";
